FROM docker.io/library/node:25-alpine

WORKDIR /app

# Install dependencies
RUN apk add chromium-chromedriver chromium

COPY . /app

ENV CHROME_BIN=/usr/bin/chromium-browser \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser \
    NODE_ENV=production \
    CHROME_DEVEL_SANDBOX=/usr/lib/chromium/chrome-sandbox

RUN npm ci --omit=dev --ignore-scripts

EXPOSE 8080

CMD ["npm", "run", "start"]